version: "3.7"
services:
  frontend:
    build: ./front
    depends_on:
      - server
    ports:
      - 4000:80
    environment:
      - REACT_APP_HOST=server
      - REACT_APP_PORT=8080
      - REACT_APP_STREAM=test

  server:
    build: ./server
    ports:
      - 1935:1935
      - 8080:8080
